#!/bin/sh

## example hotplug script

#case "$ACTION" in
#	ifup)
#		# run this code/script/function
#		# if an interface comes online
#
#		# if you want to limit it to certain interfaces you can do
#		if [ "$INTERFACE" == "wan1" ]; then
#			# run this code
#		fi
#	;;
#
#	ifdown)
#		# run this code/script/function
#		# if an interface goes offline
#	;;
#esac
